name: "Build SVN Artifacts"

on:
  workflow_call:
    inputs:
      VERSION:
        required: true
        type: string
      RC:
        required: true
        type: number

jobs:
  svn-build-artifacts:
    name: Build artifacts for SVN on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-22.04, windows-2022, macos-13, macos-14, macos-15 ]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: actions/setup-python@v5
        with:
          python-version: |
            3.9
            3.10
            3.11
            3.12

      - name: Install poetry
        run: make install-poetry

      # Publish the source distribution with the version that's in
      # the repository, otherwise the tests will fail
      - name: Compile source distribution
        run: python3 -m poetry build --format=sdist
        if: startsWith(matrix.os, 'ubuntu')

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.22.0
        with:
          output-dir: wheelhouse
          config-file: "pyproject.toml"
        env:
          # Ignore 32 bit architectures
          CIBW_ARCHS: "auto64"
          CIBW_PROJECT_REQUIRES_PYTHON: ">=3.9,<3.13"
          CIBW_TEST_REQUIRES: "pytest==7.4.2 moto==5.0.1"
          CIBW_TEST_EXTRAS: "s3fs,glue"
          CIBW_TEST_COMMAND: "pytest {project}/tests/avro/test_decoder.py"
          # There is an upstream issue with installing on MacOSX
          # https://github.com/pypa/cibuildwheel/issues/1603
          # Ignore tests for pypy since not all dependencies are compiled for it
          # and would require a local rust build chain
          CIBW_TEST_SKIP: "pp* *macosx*"

      - name: Add source distribution
        if: startsWith(matrix.os, 'ubuntu')
        run: ls -lah dist/* && cp dist/* wheelhouse/

      - uses: actions/upload-artifact@v4
        with:
          name: "svn-release-candidate-${{ matrix.os }}"
          path: ./wheelhouse/*

  svn-merge-artifacts:
    runs-on: ubuntu-latest
    needs:
      - svn-build-artifacts
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: "svn-release-candidate-${{ inputs.VERSION }}rc${{ inputs.RC }}"
          pattern: svn-release-candidate*
          delete-merged: true
